fix(admincampaignedit): fix use of lodash/pick in checkSectionSaved
This PR addresses an error that prevented admins from creating or editing campaigns; attempting to
do led to an infinite spinner and a console error: `Uncaught TypeError: #<Object> is not a function
at Array.map (<anonymous>) at AdminCampaig nEdit.checkSectionSaved (index.jsx:331)`. `pick` was
being called without the object it's meant to "pick" from.

fix #851